CREATE TABLE IF NOT EXISTS appointment
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    date_of_birth DATE         NOT NULL,
    age           VARCHAR(109) NOT NULL,
    doctor        VARCHAR(109) NOT NULL,
);

INSERT INTO appointment (name, date_of_birth, age, doctor)
VALUES ('Синявский Вяечеслав', '1980-03-11', 35, 'Ардаков Игорь'),
       ('Проскурин Илья', '2003-01-15', 21, 'Ардаков Игорь'),
       ('Родионов Сергей', '2005-10-10', 19, 'Донченко Иван'),
       ('Сыров Дмитрий', '2001-09-11', 23, 'Ардаков Игорь');
